"use client";

import { useState } from "react";
import { IconActivity as Activity, IconAlertTriangle as AlertTriangle, IconBuilding as Building2, IconCircleCheck as CheckCircle2, IconCircuitCell as CircuitBoard, IconDatabase as Database, IconPlugConnected as PlugConnected, IconRadio as Radio, IconRefresh as Refresh, IconDeviceFloppy as Save, IconShieldCheck as ShieldCheck } from "@tabler/icons-react";
import { usePersistentState } from "../use-persistent-state";
import { useActiveRole, useConfirm, useFeedback } from "../lib/contexts";
import { defaultAssetConfig, defaultChannelConfiguration, sensors } from "../lib/fixtures";
import type { ModbusByteOrder, ModbusDataType, SettingsTab } from "../lib/types";
import { useSensorData } from "../lib/use-sensor-data";

export function SettingsView() {
  const notify = useFeedback();
  const confirm = useConfirm();
  const sensors = useSensorData();
  const role = useActiveRole();
  const [tab, setTab] = useState<SettingsTab>("asset");
  const [saved, setSaved] = useState(false);
  const [connection, setConnection] = useState<"idle" | "testing" | "success">("idle");
  const [assetConfig, setAssetConfig] = usePersistentState("cam5.front.asset-config", defaultAssetConfig);
  const [gatewayConfig, setGatewayConfig] = usePersistentState("cam5.front.gateway-config", { gateway: "CAM5-GW-01", controller: "CAM5-CTRL-01", protocol: "Modbus TCP", controllerIp: "192.168.10.42", gatewayIp: "192.168.10.40", port: "502", unit: "1", polling: "2", uplink: "Ethernet / HTTPS" });
  const [channels, setChannels] = usePersistentState("cam5.front.channel-config", defaultChannelConfiguration());
  const [registerMap, setRegisterMap] = usePersistentState("cam5.front.register-map", sensors.map((sensor) => ({ id: sensor.id, label: sensor.label, reference: sensor.register.replace("HR ", ""), functionCode: "03", dataType: (sensor.type === "Temperatura" ? "Int16" : "UInt16") as ModbusDataType, scale: sensor.type === "Temperatura" ? "0.1" : "1", byteOrder: "AB" as ModbusByteOrder, unit: sensor.unit, value: sensor.value })));
  const [mapValidation, setMapValidation] = useState<"idle" | "validating" | "success" | "error">("idle");
  const duplicateReferences = new Set(registerMap.filter((row, index, rows) => rows.findIndex((candidate) => candidate.reference === row.reference) !== index).map((row) => row.reference));
  const invalidReferences = registerMap.filter((row) => !/^4\d{4}$/.test(row.reference) || Number(row.reference) < 40001 || Number(row.reference) > 49999).map((row) => row.id);
  const mappingIssues = duplicateReferences.size + invalidReferences.length;
  const thresholdIssues = channels.filter((channel) => !Number.isFinite(Number(channel.warning)) || !Number.isFinite(Number(channel.critical)) || Number(channel.warning) >= Number(channel.critical));
  const validIp = (value: string) => { const parts = value.split(".").map(Number); return parts.length === 4 && parts.every((part) => Number.isInteger(part) && part >= 0 && part <= 255); };
  const gatewayIssues = [!validIp(gatewayConfig.gatewayIp), !validIp(gatewayConfig.controllerIp), Number(gatewayConfig.port) < 1 || Number(gatewayConfig.port) > 65535, Number(gatewayConfig.unit) < 0 || Number(gatewayConfig.unit) > 247, Number(gatewayConfig.polling) < 1].filter(Boolean).length;
  const configurationIssues = mappingIssues + thresholdIssues.length + gatewayIssues;
  const saveChanges = () => { if (configurationIssues) { setTab(thresholdIssues.length ? "channels" : mappingIssues ? "registers" : "gateway"); notify(`Hay ${configurationIssues} campo${configurationIssues === 1 ? "" : "s"} por corregir antes de guardar.`, "warning"); return; } setSaved(true); notify("Configuración validada y guardada en este entorno de demostración."); window.setTimeout(() => setSaved(false), 2400); };
  const testConnection = () => { setConnection("testing"); window.setTimeout(() => { setConnection("success"); notify("Prueba Modbus completada correctamente."); }, 900); };
  const updateChannel = (id: string, field: "enabled" | "warning" | "critical", value: boolean | string) => { const apply = () => setChannels((current) => current.map((item) => item.id === id ? { ...item, [field]: value } : item)); if (field === "enabled" && value === false) confirm({ title: `Desactivar canal ${id}`, detail: "El canal dejará de aparecer en tendencias, reportes e indicadores operativos.", confirmLabel: "Desactivar canal", tone: "danger", onConfirm: apply }); else apply(); };
  const updateRegister = (id: string, field: "reference" | "dataType" | "scale" | "byteOrder", value: string) => { setMapValidation("idle"); setRegisterMap((current) => current.map((row) => row.id === id ? { ...row, [field]: value } : row)); };
  const validateRegisterMap = () => { setMapValidation("validating"); window.setTimeout(() => { setMapValidation(mappingIssues ? "error" : "success"); notify(mappingIssues ? `${mappingIssues} conflicto${mappingIssues === 1 ? "" : "s"} en el mapa Modbus.` : "Mapa Modbus validado sin conflictos.", mappingIssues ? "warning" : "success"); }, 700); };

  return (
    <article className={`panel module-panel settings-module ${role === "Solo lectura" ? "role-readonly" : ""}`}>
      <div className="module-toolbar">
        <div className="module-tabs" role="tablist" aria-label="Secciones de configuración">
          <button className={tab === "asset" ? "active" : ""} onClick={() => setTab("asset")}><Building2 size={16} /> Activo</button>
          <button className={tab === "channels" ? "active" : ""} onClick={() => setTab("channels")}><Activity size={16} /> Canales y umbrales</button>
          <button className={tab === "registers" ? "active" : ""} onClick={() => setTab("registers")}><Database size={16} /> Mapa Modbus</button>
          <button className={tab === "gateway" ? "active" : ""} onClick={() => setTab("gateway")}><PlugConnected size={16} /> Gateway + Modbus</button>
        </div>
        <button className={`save-config-button ${saved ? "saved" : ""}`} onClick={saveChanges}>{saved ? <CheckCircle2 size={16} /> : <Save size={16} />}{saved ? "Cambios guardados" : "Guardar cambios"}</button>
      </div>
      {configurationIssues > 0 && <div className="validation-summary" role="alert"><AlertTriangle size={17} /><div><strong>Configuración pendiente de validar</strong><p>{thresholdIssues.length} umbrales · {mappingIssues} conflictos Modbus · {gatewayIssues} parámetros de comunicación.</p></div></div>}

      {tab === "asset" && <div className="settings-content"><div className="settings-section-head"><span className="settings-icon"><Building2 size={20} /></span><div><h2>Identificación del activo</h2><p>Datos utilizados en navegación, reportes y trazabilidad.</p></div></div><div className="form-grid"><label><span>Código del activo</span><input value={assetConfig.name} onChange={(event) => setAssetConfig({ ...assetConfig, name: event.target.value })} /></label><label><span>Descripción</span><input value={assetConfig.description} onChange={(event) => setAssetConfig({ ...assetConfig, description: event.target.value })} /></label><label><span>Tensión nominal</span><div className="input-unit"><input value={assetConfig.voltage} onChange={(event) => setAssetConfig({ ...assetConfig, voltage: event.target.value })} /><b>kV</b></div></label><label><span>Ubicación fija</span><input value={assetConfig.location} readOnly /></label><label className="form-span-2"><span>Zona horaria</span><select value={assetConfig.timezone} onChange={(event) => setAssetConfig({ ...assetConfig, timezone: event.target.value })}><option>America/Santiago</option><option>UTC</option></select></label></div><div className="configuration-note"><ShieldCheck size={17} /><p><strong>Despliegue monositio.</strong> Todos los activos pertenecen a Subestación Norte y comparten el gateway CAM5-GW-01.</p></div></div>}

      {tab === "channels" && <div className="settings-content channels-settings"><div className="settings-section-head"><span className="settings-icon"><Activity size={20} /></span><div><h2>Canales y umbrales</h2><p>Habilita señales y define niveles operativos de alarma.</p></div></div><div className="channel-config-table"><div className="channel-config-head"><span>Canal</span><span>Registro</span><span>Advertencia</span><span>Crítico</span><span>Estado</span></div>{channels.map((channel) => <div className="channel-config-row" key={channel.id}><span className="history-channel"><b className={`sensor-code sensor-${channel.state}`}>{channel.id}</b><span><strong>{channel.label}</strong><small>{channel.type}</small></span></span><span className="mono-cell">{channel.register}</span><label className="compact-input"><input value={channel.warning} onChange={(event) => updateChannel(channel.id, "warning", event.target.value)} /><b>{channel.unit}</b></label><label className="compact-input"><input value={channel.critical} onChange={(event) => updateChannel(channel.id, "critical", event.target.value)} /><b>{channel.unit}</b></label><button className={`channel-toggle ${channel.enabled ? "on" : ""}`} onClick={() => updateChannel(channel.id, "enabled", !channel.enabled)}><i />{channel.enabled ? "Activo" : "Inactivo"}</button></div>)}</div></div>}

      {tab === "registers" && <div className="settings-content register-settings">
        <div className="register-settings-head">
          <div className="settings-section-head"><span className="settings-icon"><Database size={20} /></span><div><h2>Mapa de registros Modbus</h2><p>Define cómo CAM5-CTRL-01 expone cada señal al gateway único.</p></div></div>
          <button className={`register-validate-button ${mapValidation}`} onClick={validateRegisterMap} disabled={mapValidation === "validating"}>{mapValidation === "validating" ? <><Refresh size={15} /> Validando…</> : mapValidation === "success" ? <><CheckCircle2 size={15} /> Mapa válido</> : mapValidation === "error" ? <><AlertTriangle size={15} /> Revisar mapa</> : <><ShieldCheck size={15} /> Validar mapa</>}</button>
        </div>
        <div className="register-map-summary">
          <article><small>Registros configurados</small><strong>{registerMap.length}</strong><span>{channels.filter((channel) => channel.enabled).length} canales activos</span></article>
          <article><small>Función de lectura</small><strong>FC 03</strong><span>Holding Registers</span></article>
          <article className={mappingIssues ? "has-issues" : "is-valid"}><small>Conflictos detectados</small><strong>{mappingIssues}</strong><span>{mappingIssues ? "Corregir antes de conectar" : "Referencias únicas y válidas"}</span></article>
        </div>
        <div className="modbus-address-note"><CircuitBoard size={17} /><div><strong>Referencia visible versus offset del protocolo</strong><p>El portal muestra la referencia 4xxxx para facilitar la lectura técnica. El driver utilizará el offset base 0; por ejemplo, 40001 corresponde al offset 0.</p></div></div>
        <div className="register-map-scroll"><div className="register-map-table">
          <div className="register-map-row register-map-header"><span>Canal</span><span>Referencia 4xxxx</span><span>Offset base 0</span><span>Función</span><span>Tipo de dato</span><span>Escala</span><span>Orden</span><span>Lectura actual</span></div>
          {registerMap.map((row) => { const invalid = invalidReferences.includes(row.id) || duplicateReferences.has(row.reference); const offset = /^4\d{4}$/.test(row.reference) ? Number(row.reference) - 40001 : null; return <div className={`register-map-row ${invalid ? "row-invalid" : ""}`} key={row.id}><span className="register-channel"><b className={`sensor-code sensor-${sensors.find((sensor) => sensor.id === row.id)?.state ?? "normal"}`}>{row.id}</b><span><strong>{row.label}</strong><small>{row.unit}</small></span></span><label><input value={row.reference} onChange={(event) => updateRegister(row.id, "reference", event.target.value)} aria-label={`Referencia Modbus ${row.id}`} />{invalid && <small>Referencia inválida o duplicada</small>}</label><span className="register-offset">{offset !== null && offset >= 0 ? offset : "—"}</span><span className="register-function"><b>03</b><small>Holding</small></span><label><select value={row.dataType} onChange={(event) => updateRegister(row.id, "dataType", event.target.value)} aria-label={`Tipo de dato ${row.id}`}><option>Int16</option><option>UInt16</option></select></label><label className="register-scale"><input value={row.scale} onChange={(event) => updateRegister(row.id, "scale", event.target.value)} aria-label={`Escala ${row.id}`} /><b>×</b></label><label><select value={row.byteOrder} onChange={(event) => updateRegister(row.id, "byteOrder", event.target.value)} aria-label={`Orden de bytes ${row.id}`}><option>AB</option><option>BA</option></select></label><span className="register-live-value"><i /><strong>{row.value} {row.unit}</strong><small>Calidad válida</small></span></div>; })}
        </div></div>
        <div className="configuration-note"><ShieldCheck size={17} /><p><strong>Mapa asumido para el frontend.</strong> Las referencias, tipos y escalas deben confirmarse contra la documentación final del controlador antes de habilitar lecturas reales.</p></div>
      </div>}

      {tab === "gateway" && <div className="settings-content"><div className="settings-section-head"><span className="settings-icon"><PlugConnected size={20} /></span><div><h2>Gateway y controlador Modbus</h2><p>Arquitectura única de adquisición para Subestación Norte.</p></div></div><div className="single-stack-note"><Radio size={18} /><div><strong>CAM5-CTRL-01 → CAM5-GW-01 → CAM5 CORE</strong><p>El controlador concentra los registros Modbus TCP. El gateway transporta la telemetría hacia la plataforma.</p></div></div><div className="gateway-layout"><div className="form-grid"><label><span>Gateway único</span><input value={gatewayConfig.gateway} readOnly /></label><label><span>IP del gateway</span><input value={gatewayConfig.gatewayIp} onChange={(event) => setGatewayConfig({ ...gatewayConfig, gatewayIp: event.target.value })} /></label><label><span>Enlace hacia CAM5 CORE</span><input value={gatewayConfig.uplink} readOnly /></label><label><span>Controlador Modbus</span><input value={gatewayConfig.controller} readOnly /></label><label><span>Protocolo de campo</span><select value={gatewayConfig.protocol} onChange={(event) => setGatewayConfig({ ...gatewayConfig, protocol: event.target.value })}><option>Modbus TCP</option></select></label><label><span>IP del controlador</span><input value={gatewayConfig.controllerIp} onChange={(event) => setGatewayConfig({ ...gatewayConfig, controllerIp: event.target.value })} /></label><label><span>Puerto Modbus</span><input value={gatewayConfig.port} onChange={(event) => setGatewayConfig({ ...gatewayConfig, port: event.target.value })} /></label><label><span>Unit ID</span><input value={gatewayConfig.unit} onChange={(event) => setGatewayConfig({ ...gatewayConfig, unit: event.target.value })} /></label><label><span>Intervalo de lectura</span><div className="input-unit"><input value={gatewayConfig.polling} onChange={(event) => setGatewayConfig({ ...gatewayConfig, polling: event.target.value })} /><b>s</b></div></label></div><aside className="connection-test-card"><span className={`connection-test-icon ${connection}`}><Radio size={24} /></span><h3>Controlador CAM5-CTRL-01</h3><p>Valida acceso, puerto y respuesta Modbus desde el gateway único.</p><dl><div><dt>Destino</dt><dd>{gatewayConfig.controllerIp}:{gatewayConfig.port}</dd></div><div><dt>Gateway</dt><dd>{gatewayConfig.gateway}</dd></div><div><dt>Timeout</dt><dd>3 segundos</dd></div></dl><button onClick={testConnection} disabled={connection === "testing"}>{connection === "testing" ? "Probando…" : connection === "success" ? <><CheckCircle2 size={15} /> Controlador disponible</> : <><PlugConnected size={15} /> Probar Modbus</>}</button></aside></div></div>}
    </article>
  );
}
